CREATE TABLE taxs (
  id SERIAL PRIMARY KEY,
  order_id INT,
  name VARCHAR(50),
  tax DECIMAL(10,2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);