services:
  app:
    build: .
    container_name: justsruput_backend
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db: 
    image: postgres:16-alpine
    container_name: justsruput_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:7-alpine
    container_name: justsruput_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    restart: always

volumes:
  postgres_data: